# Generated by Django 2.0 on 2018-08-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_org_name', models.CharField(blank=True, max_length=39)),
                ('github_org_url', models.URLField(blank=True, max_length=2000)),
                ('github_org_api_url', models.URLField(blank=True, max_length=2000)),
                ('profile_allow_biography', models.BooleanField(default=True)),
                ('profile_allow_name_changes', models.BooleanField(default=False)),
                ('profile_allow_username_changes', models.BooleanField(default=False)),
                ('profile_allow_change_requests', models.BooleanField(default=True)),
                ('users_show_completed_tasks', models.BooleanField(default=True)),
                ('users_show_email', models.BooleanField(default=True)),
                ('users_show_online', models.BooleanField(default=True)),
                ('tasks_show_xp_bar', models.BooleanField(default=True)),
                ('settings_initialised', models.BooleanField(default=False)),
                ('settings_setup_code', models.CharField(blank=True, max_length=19)),
            ],
        ),
    ]
