# Generated by Django 2.0 on 2018-03-04 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_auto_20180304_1212'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_image', models.CharField(default='/accounts/images/default_avatar.png', max_length=1000)),
                ('gravatar_url', models.CharField(default='', max_length=1000)),
                ('gravatar_enabled', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('biography', models.CharField(blank=True, max_length=300)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('current_task', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
