# Generated by Django 2.0 on 2018-03-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
