# Generated by Django 2.0 on 2018-03-21 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180321_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.URLField(blank=True, max_length=2000, validators=[django.core.validators.URLValidator]),
        ),
    ]
