# Generated by Django 2.0 on 2018-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180321_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gravatar_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
