# Generated by Django 2.0 on 2018-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='associated_background',
            field=models.CharField(default='/accounts/images/default_avatar.png', max_length=1000),
        ),
    ]
