# Generated by Django 2.0 on 2018-05-31 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_associated_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_action',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
