# Generated by Django 2.0 on 2018-06-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180601_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='associated_background',
            field=models.CharField(default='/accounts/images/catground_sample.jpg', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
