# Generated by Django 2.0 on 2018-06-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180603_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='associated_image',
            field=models.ImageField(default='/accounts/images/default_avatar.png', upload_to='user_content/profile_images/'),
        ),
    ]
