# Generated by Django 2.0 on 2018-06-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180619_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='associated_image',
            new_name='avatar',
        ),
    ]
