# Generated by Django 2.0 on 2018-06-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180619_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='associated_background',
            new_name='background',
        ),
    ]
