# Generated by Django 2.0 on 2018-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180619_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gravatar_enabled',
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank=True, upload_to='profile_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gravatar_url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
