# Generated by Django 2.0 on 2018-06-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180619_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='background_version',
            field=models.IntegerField(default=0),
        ),
    ]
