# Generated by Django 2.0 on 2018-06-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180621_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gravatar_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
