# Generated by Django 2.0 on 2018-07-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_gravatar_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='server_owner',
            field=models.BooleanField(default=False),
        ),
    ]
