# Generated by Django 2.0 on 2018-03-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='settings_setup_code1',
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
