# Generated by Django 2.0 on 2018-03-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0002_settings_settings_setup_code1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='settings_setup_code1',
        ),
    ]
