# Generated by Django 2.0 on 2018-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0003_remove_settings_settings_setup_code1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='github_integrated',
        ),
        migrations.AddField(
            model_name='settings',
            name='github_organisation',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
