# Generated by Django 2.0 on 2018-07-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0004_auto_20180729_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='github_organisation',
        ),
        migrations.AddField(
            model_name='settings',
            name='github_organisation_name',
            field=models.CharField(blank=True, max_length=39),
        ),
        migrations.AddField(
            model_name='settings',
            name='github_organisation_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
