# Generated by Django 2.0 on 2018-07-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0009_auto_20180729_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='github_organisation_url',
            new_name='github_org_url',
        ),
    ]
