# Generated by Django 2.0 on 2018-07-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cAdmin', '0012_remove_settings_github_org_repos_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='github_org_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
