# Generated by Django 2.0 on 2018-01-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_owner', models.CharField(max_length=15)),
                ('task_priority', models.IntegerField()),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('deadline_date', models.DateTimeField(verbose_name='deadline')),
            ],
        ),
    ]
