# Generated by Django 2.0 on 2018-08-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bumped',
            field=models.BooleanField(default=False),
        ),
    ]
