# Generated by Django 2.0 on 2018-01-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180103_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_open',
            field=models.BooleanField(default=True),
        ),
    ]
