# Generated by Django 2.1 on 2018-09-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180803_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bump_date',
        ),
    ]
