# Generated by Django 2.0 on 2018-01-06 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20180106_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
