# Generated by Django 2.1 on 2018-09-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_bump_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_bumped',
            field=models.BooleanField(default=False),
        ),
    ]
