# Generated by Django 2.1 on 2018-09-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_task_bumped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_bumped',
            new_name='is_bumped',
        ),
    ]
