# Generated by Django 2.1 on 2018-09-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20180918_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_bumped',
            new_name='is_pinned',
        ),
    ]
