# Generated by Django 2.0 on 2018-01-09 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0007_taskdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskData',
            new_name='Profile',
        ),
    ]
