# Generated by Django 2.0 on 2018-01-10 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180109_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
