# Generated by Django 2.0 on 2018-01-23 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_task_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_size',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
    ]
