# Generated by Django 2.0 on 2018-01-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20180123_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='associated_image',
            field=models.CharField(default='/accounts/images/default_avatar.png', max_length=1000),
        ),
    ]
