# Generated by Django 2.0 on 2018-01-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_profile_associated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_quest',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
