# Generated by Django 2.0 on 2018-01-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20180129_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='quest_stage',
            field=models.IntegerField(default=0),
        ),
    ]
