# Generated by Django 2.0 on 2018-01-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_quest_quest_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='quest_position',
            field=models.IntegerField(default=-1),
        ),
    ]
