# Generated by Django 2.0 on 2018-02-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_quest_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.CharField(default='UNK', max_length=20),
            preserve_default=False,
        ),
    ]
