# Generated by Django 2.0 on 2018-02-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_profile_current_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
