# Generated by Django 2.0 on 2018-02-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20180219_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_task',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
