# Generated by Django 2.0 on 2018-02-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20180219_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gravatar_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='gravatar_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
